//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCBookDBEntities : DbContext
    {
        public MVCBookDBEntities()
            : base("name=MVCBookDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author> authors { get; set; }
        public DbSet<authorbook> authorbooks { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<postage> postages { get; set; }
        public DbSet<review> reviews { get; set; }
    }
}
