//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorbook
    {
        public string authorbookid { get; set; }
        public string bookid { get; set; }
        public string authorid { get; set; }
    
        public virtual author author { get; set; }
        public virtual book book { get; set; }
    }
}
