//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public author()
        {
            this.authorbooks = new HashSet<authorbook>();
        }
    
        public string authorid { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<authorbook> authorbooks { get; set; }
    }
}
