//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.authorbooks = new HashSet<authorbook>();
            this.reviews = new HashSet<review>();
        }
    
        public string bookid { get; set; }
        public string availability { get; set; }
        public string booktype { get; set; }
        public string publisher { get; set; }
        public string isbn { get; set; }
        public Nullable<short> itemsinstock { get; set; }
        public Nullable<decimal> price { get; set; }
        public string title { get; set; }
        public byte[] picture { get; set; }
    
        public virtual ICollection<authorbook> authorbooks { get; set; }
        public virtual ICollection<review> reviews { get; set; }
    }
}
